// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package hajji.mohammed.stubs;

public final class Schema {
  private Schema() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code Currency}
   */
  public enum Currency
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>EURO = 1;</code>
     */
    EURO(1),
    /**
     * <code>USD = 2;</code>
     */
    USD(2),
    /**
     * <code>DH = 3;</code>
     */
    DH(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>EURO = 1;</code>
     */
    public static final int EURO_VALUE = 1;
    /**
     * <code>USD = 2;</code>
     */
    public static final int USD_VALUE = 2;
    /**
     * <code>DH = 3;</code>
     */
    public static final int DH_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Currency valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Currency forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return EURO;
        case 2: return USD;
        case 3: return DH;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Currency>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Currency> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Currency>() {
            public Currency findValueByNumber(int number) {
              return Currency.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return hajji.mohammed.stubs.Schema.getDescriptor().getEnumTypes().get(0);
    }

    private static final Currency[] VALUES = values();

    public static Currency valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Currency(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Currency)
  }

  public interface ObjectRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ObjectRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Currency from = 1;</code>
     * @return The enum numeric value on the wire for from.
     */
    int getFromValue();
    /**
     * <code>.Currency from = 1;</code>
     * @return The from.
     */
    hajji.mohammed.stubs.Schema.Currency getFrom();

    /**
     * <code>.Currency to = 2;</code>
     * @return The enum numeric value on the wire for to.
     */
    int getToValue();
    /**
     * <code>.Currency to = 2;</code>
     * @return The to.
     */
    hajji.mohammed.stubs.Schema.Currency getTo();

    /**
     * <code>double amount = 3;</code>
     * @return The amount.
     */
    double getAmount();
  }
  /**
   * Protobuf type {@code ObjectRequest}
   */
  public  static final class ObjectRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ObjectRequest)
      ObjectRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ObjectRequest.newBuilder() to construct.
    private ObjectRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ObjectRequest() {
      from_ = 0;
      to_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ObjectRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ObjectRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              from_ = rawValue;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              to_ = rawValue;
              break;
            }
            case 25: {

              amount_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hajji.mohammed.stubs.Schema.internal_static_ObjectRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hajji.mohammed.stubs.Schema.internal_static_ObjectRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hajji.mohammed.stubs.Schema.ObjectRequest.class, hajji.mohammed.stubs.Schema.ObjectRequest.Builder.class);
    }

    public static final int FROM_FIELD_NUMBER = 1;
    private int from_;
    /**
     * <code>.Currency from = 1;</code>
     * @return The enum numeric value on the wire for from.
     */
    public int getFromValue() {
      return from_;
    }
    /**
     * <code>.Currency from = 1;</code>
     * @return The from.
     */
    public hajji.mohammed.stubs.Schema.Currency getFrom() {
      @SuppressWarnings("deprecation")
      hajji.mohammed.stubs.Schema.Currency result = hajji.mohammed.stubs.Schema.Currency.valueOf(from_);
      return result == null ? hajji.mohammed.stubs.Schema.Currency.UNRECOGNIZED : result;
    }

    public static final int TO_FIELD_NUMBER = 2;
    private int to_;
    /**
     * <code>.Currency to = 2;</code>
     * @return The enum numeric value on the wire for to.
     */
    public int getToValue() {
      return to_;
    }
    /**
     * <code>.Currency to = 2;</code>
     * @return The to.
     */
    public hajji.mohammed.stubs.Schema.Currency getTo() {
      @SuppressWarnings("deprecation")
      hajji.mohammed.stubs.Schema.Currency result = hajji.mohammed.stubs.Schema.Currency.valueOf(to_);
      return result == null ? hajji.mohammed.stubs.Schema.Currency.UNRECOGNIZED : result;
    }

    public static final int AMOUNT_FIELD_NUMBER = 3;
    private double amount_;
    /**
     * <code>double amount = 3;</code>
     * @return The amount.
     */
    public double getAmount() {
      return amount_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (from_ != hajji.mohammed.stubs.Schema.Currency.UNKNOWN.getNumber()) {
        output.writeEnum(1, from_);
      }
      if (to_ != hajji.mohammed.stubs.Schema.Currency.UNKNOWN.getNumber()) {
        output.writeEnum(2, to_);
      }
      if (amount_ != 0D) {
        output.writeDouble(3, amount_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (from_ != hajji.mohammed.stubs.Schema.Currency.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, from_);
      }
      if (to_ != hajji.mohammed.stubs.Schema.Currency.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, to_);
      }
      if (amount_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, amount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof hajji.mohammed.stubs.Schema.ObjectRequest)) {
        return super.equals(obj);
      }
      hajji.mohammed.stubs.Schema.ObjectRequest other = (hajji.mohammed.stubs.Schema.ObjectRequest) obj;

      if (from_ != other.from_) return false;
      if (to_ != other.to_) return false;
      if (java.lang.Double.doubleToLongBits(getAmount())
          != java.lang.Double.doubleToLongBits(
              other.getAmount())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + from_;
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + to_;
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAmount()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static hajji.mohammed.stubs.Schema.ObjectRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hajji.mohammed.stubs.Schema.ObjectRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hajji.mohammed.stubs.Schema.ObjectRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hajji.mohammed.stubs.Schema.ObjectRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hajji.mohammed.stubs.Schema.ObjectRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hajji.mohammed.stubs.Schema.ObjectRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hajji.mohammed.stubs.Schema.ObjectRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static hajji.mohammed.stubs.Schema.ObjectRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static hajji.mohammed.stubs.Schema.ObjectRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static hajji.mohammed.stubs.Schema.ObjectRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static hajji.mohammed.stubs.Schema.ObjectRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static hajji.mohammed.stubs.Schema.ObjectRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(hajji.mohammed.stubs.Schema.ObjectRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ObjectRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ObjectRequest)
        hajji.mohammed.stubs.Schema.ObjectRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hajji.mohammed.stubs.Schema.internal_static_ObjectRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hajji.mohammed.stubs.Schema.internal_static_ObjectRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hajji.mohammed.stubs.Schema.ObjectRequest.class, hajji.mohammed.stubs.Schema.ObjectRequest.Builder.class);
      }

      // Construct using hajji.mohammed.stubs.Schema.ObjectRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        from_ = 0;

        to_ = 0;

        amount_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hajji.mohammed.stubs.Schema.internal_static_ObjectRequest_descriptor;
      }

      @java.lang.Override
      public hajji.mohammed.stubs.Schema.ObjectRequest getDefaultInstanceForType() {
        return hajji.mohammed.stubs.Schema.ObjectRequest.getDefaultInstance();
      }

      @java.lang.Override
      public hajji.mohammed.stubs.Schema.ObjectRequest build() {
        hajji.mohammed.stubs.Schema.ObjectRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public hajji.mohammed.stubs.Schema.ObjectRequest buildPartial() {
        hajji.mohammed.stubs.Schema.ObjectRequest result = new hajji.mohammed.stubs.Schema.ObjectRequest(this);
        result.from_ = from_;
        result.to_ = to_;
        result.amount_ = amount_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hajji.mohammed.stubs.Schema.ObjectRequest) {
          return mergeFrom((hajji.mohammed.stubs.Schema.ObjectRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hajji.mohammed.stubs.Schema.ObjectRequest other) {
        if (other == hajji.mohammed.stubs.Schema.ObjectRequest.getDefaultInstance()) return this;
        if (other.from_ != 0) {
          setFromValue(other.getFromValue());
        }
        if (other.to_ != 0) {
          setToValue(other.getToValue());
        }
        if (other.getAmount() != 0D) {
          setAmount(other.getAmount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        hajji.mohammed.stubs.Schema.ObjectRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (hajji.mohammed.stubs.Schema.ObjectRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int from_ = 0;
      /**
       * <code>.Currency from = 1;</code>
       * @return The enum numeric value on the wire for from.
       */
      public int getFromValue() {
        return from_;
      }
      /**
       * <code>.Currency from = 1;</code>
       * @param value The enum numeric value on the wire for from to set.
       * @return This builder for chaining.
       */
      public Builder setFromValue(int value) {
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Currency from = 1;</code>
       * @return The from.
       */
      public hajji.mohammed.stubs.Schema.Currency getFrom() {
        @SuppressWarnings("deprecation")
        hajji.mohammed.stubs.Schema.Currency result = hajji.mohammed.stubs.Schema.Currency.valueOf(from_);
        return result == null ? hajji.mohammed.stubs.Schema.Currency.UNRECOGNIZED : result;
      }
      /**
       * <code>.Currency from = 1;</code>
       * @param value The from to set.
       * @return This builder for chaining.
       */
      public Builder setFrom(hajji.mohammed.stubs.Schema.Currency value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        from_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Currency from = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFrom() {
        
        from_ = 0;
        onChanged();
        return this;
      }

      private int to_ = 0;
      /**
       * <code>.Currency to = 2;</code>
       * @return The enum numeric value on the wire for to.
       */
      public int getToValue() {
        return to_;
      }
      /**
       * <code>.Currency to = 2;</code>
       * @param value The enum numeric value on the wire for to to set.
       * @return This builder for chaining.
       */
      public Builder setToValue(int value) {
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Currency to = 2;</code>
       * @return The to.
       */
      public hajji.mohammed.stubs.Schema.Currency getTo() {
        @SuppressWarnings("deprecation")
        hajji.mohammed.stubs.Schema.Currency result = hajji.mohammed.stubs.Schema.Currency.valueOf(to_);
        return result == null ? hajji.mohammed.stubs.Schema.Currency.UNRECOGNIZED : result;
      }
      /**
       * <code>.Currency to = 2;</code>
       * @param value The to to set.
       * @return This builder for chaining.
       */
      public Builder setTo(hajji.mohammed.stubs.Schema.Currency value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        to_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Currency to = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTo() {
        
        to_ = 0;
        onChanged();
        return this;
      }

      private double amount_ ;
      /**
       * <code>double amount = 3;</code>
       * @return The amount.
       */
      public double getAmount() {
        return amount_;
      }
      /**
       * <code>double amount = 3;</code>
       * @param value The amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmount(double value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double amount = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmount() {
        
        amount_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ObjectRequest)
    }

    // @@protoc_insertion_point(class_scope:ObjectRequest)
    private static final hajji.mohammed.stubs.Schema.ObjectRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new hajji.mohammed.stubs.Schema.ObjectRequest();
    }

    public static hajji.mohammed.stubs.Schema.ObjectRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ObjectRequest>
        PARSER = new com.google.protobuf.AbstractParser<ObjectRequest>() {
      @java.lang.Override
      public ObjectRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ObjectRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ObjectRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ObjectRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public hajji.mohammed.stubs.Schema.ObjectRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ObjectResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ObjectResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Currency from = 1;</code>
     * @return The enum numeric value on the wire for from.
     */
    int getFromValue();
    /**
     * <code>.Currency from = 1;</code>
     * @return The from.
     */
    hajji.mohammed.stubs.Schema.Currency getFrom();

    /**
     * <code>.Currency to = 2;</code>
     * @return The enum numeric value on the wire for to.
     */
    int getToValue();
    /**
     * <code>.Currency to = 2;</code>
     * @return The to.
     */
    hajji.mohammed.stubs.Schema.Currency getTo();

    /**
     * <code>double amount = 3;</code>
     * @return The amount.
     */
    double getAmount();

    /**
     * <code>double result = 4;</code>
     * @return The result.
     */
    double getResult();
  }
  /**
   * Protobuf type {@code ObjectResponse}
   */
  public  static final class ObjectResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ObjectResponse)
      ObjectResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ObjectResponse.newBuilder() to construct.
    private ObjectResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ObjectResponse() {
      from_ = 0;
      to_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ObjectResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ObjectResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              from_ = rawValue;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              to_ = rawValue;
              break;
            }
            case 25: {

              amount_ = input.readDouble();
              break;
            }
            case 33: {

              result_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hajji.mohammed.stubs.Schema.internal_static_ObjectResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hajji.mohammed.stubs.Schema.internal_static_ObjectResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hajji.mohammed.stubs.Schema.ObjectResponse.class, hajji.mohammed.stubs.Schema.ObjectResponse.Builder.class);
    }

    public static final int FROM_FIELD_NUMBER = 1;
    private int from_;
    /**
     * <code>.Currency from = 1;</code>
     * @return The enum numeric value on the wire for from.
     */
    public int getFromValue() {
      return from_;
    }
    /**
     * <code>.Currency from = 1;</code>
     * @return The from.
     */
    public hajji.mohammed.stubs.Schema.Currency getFrom() {
      @SuppressWarnings("deprecation")
      hajji.mohammed.stubs.Schema.Currency result = hajji.mohammed.stubs.Schema.Currency.valueOf(from_);
      return result == null ? hajji.mohammed.stubs.Schema.Currency.UNRECOGNIZED : result;
    }

    public static final int TO_FIELD_NUMBER = 2;
    private int to_;
    /**
     * <code>.Currency to = 2;</code>
     * @return The enum numeric value on the wire for to.
     */
    public int getToValue() {
      return to_;
    }
    /**
     * <code>.Currency to = 2;</code>
     * @return The to.
     */
    public hajji.mohammed.stubs.Schema.Currency getTo() {
      @SuppressWarnings("deprecation")
      hajji.mohammed.stubs.Schema.Currency result = hajji.mohammed.stubs.Schema.Currency.valueOf(to_);
      return result == null ? hajji.mohammed.stubs.Schema.Currency.UNRECOGNIZED : result;
    }

    public static final int AMOUNT_FIELD_NUMBER = 3;
    private double amount_;
    /**
     * <code>double amount = 3;</code>
     * @return The amount.
     */
    public double getAmount() {
      return amount_;
    }

    public static final int RESULT_FIELD_NUMBER = 4;
    private double result_;
    /**
     * <code>double result = 4;</code>
     * @return The result.
     */
    public double getResult() {
      return result_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (from_ != hajji.mohammed.stubs.Schema.Currency.UNKNOWN.getNumber()) {
        output.writeEnum(1, from_);
      }
      if (to_ != hajji.mohammed.stubs.Schema.Currency.UNKNOWN.getNumber()) {
        output.writeEnum(2, to_);
      }
      if (amount_ != 0D) {
        output.writeDouble(3, amount_);
      }
      if (result_ != 0D) {
        output.writeDouble(4, result_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (from_ != hajji.mohammed.stubs.Schema.Currency.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, from_);
      }
      if (to_ != hajji.mohammed.stubs.Schema.Currency.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, to_);
      }
      if (amount_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, amount_);
      }
      if (result_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, result_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof hajji.mohammed.stubs.Schema.ObjectResponse)) {
        return super.equals(obj);
      }
      hajji.mohammed.stubs.Schema.ObjectResponse other = (hajji.mohammed.stubs.Schema.ObjectResponse) obj;

      if (from_ != other.from_) return false;
      if (to_ != other.to_) return false;
      if (java.lang.Double.doubleToLongBits(getAmount())
          != java.lang.Double.doubleToLongBits(
              other.getAmount())) return false;
      if (java.lang.Double.doubleToLongBits(getResult())
          != java.lang.Double.doubleToLongBits(
              other.getResult())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + from_;
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + to_;
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAmount()));
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getResult()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static hajji.mohammed.stubs.Schema.ObjectResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hajji.mohammed.stubs.Schema.ObjectResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hajji.mohammed.stubs.Schema.ObjectResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hajji.mohammed.stubs.Schema.ObjectResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hajji.mohammed.stubs.Schema.ObjectResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hajji.mohammed.stubs.Schema.ObjectResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hajji.mohammed.stubs.Schema.ObjectResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static hajji.mohammed.stubs.Schema.ObjectResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static hajji.mohammed.stubs.Schema.ObjectResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static hajji.mohammed.stubs.Schema.ObjectResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static hajji.mohammed.stubs.Schema.ObjectResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static hajji.mohammed.stubs.Schema.ObjectResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(hajji.mohammed.stubs.Schema.ObjectResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ObjectResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ObjectResponse)
        hajji.mohammed.stubs.Schema.ObjectResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hajji.mohammed.stubs.Schema.internal_static_ObjectResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hajji.mohammed.stubs.Schema.internal_static_ObjectResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hajji.mohammed.stubs.Schema.ObjectResponse.class, hajji.mohammed.stubs.Schema.ObjectResponse.Builder.class);
      }

      // Construct using hajji.mohammed.stubs.Schema.ObjectResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        from_ = 0;

        to_ = 0;

        amount_ = 0D;

        result_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hajji.mohammed.stubs.Schema.internal_static_ObjectResponse_descriptor;
      }

      @java.lang.Override
      public hajji.mohammed.stubs.Schema.ObjectResponse getDefaultInstanceForType() {
        return hajji.mohammed.stubs.Schema.ObjectResponse.getDefaultInstance();
      }

      @java.lang.Override
      public hajji.mohammed.stubs.Schema.ObjectResponse build() {
        hajji.mohammed.stubs.Schema.ObjectResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public hajji.mohammed.stubs.Schema.ObjectResponse buildPartial() {
        hajji.mohammed.stubs.Schema.ObjectResponse result = new hajji.mohammed.stubs.Schema.ObjectResponse(this);
        result.from_ = from_;
        result.to_ = to_;
        result.amount_ = amount_;
        result.result_ = result_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hajji.mohammed.stubs.Schema.ObjectResponse) {
          return mergeFrom((hajji.mohammed.stubs.Schema.ObjectResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hajji.mohammed.stubs.Schema.ObjectResponse other) {
        if (other == hajji.mohammed.stubs.Schema.ObjectResponse.getDefaultInstance()) return this;
        if (other.from_ != 0) {
          setFromValue(other.getFromValue());
        }
        if (other.to_ != 0) {
          setToValue(other.getToValue());
        }
        if (other.getAmount() != 0D) {
          setAmount(other.getAmount());
        }
        if (other.getResult() != 0D) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        hajji.mohammed.stubs.Schema.ObjectResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (hajji.mohammed.stubs.Schema.ObjectResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int from_ = 0;
      /**
       * <code>.Currency from = 1;</code>
       * @return The enum numeric value on the wire for from.
       */
      public int getFromValue() {
        return from_;
      }
      /**
       * <code>.Currency from = 1;</code>
       * @param value The enum numeric value on the wire for from to set.
       * @return This builder for chaining.
       */
      public Builder setFromValue(int value) {
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Currency from = 1;</code>
       * @return The from.
       */
      public hajji.mohammed.stubs.Schema.Currency getFrom() {
        @SuppressWarnings("deprecation")
        hajji.mohammed.stubs.Schema.Currency result = hajji.mohammed.stubs.Schema.Currency.valueOf(from_);
        return result == null ? hajji.mohammed.stubs.Schema.Currency.UNRECOGNIZED : result;
      }
      /**
       * <code>.Currency from = 1;</code>
       * @param value The from to set.
       * @return This builder for chaining.
       */
      public Builder setFrom(hajji.mohammed.stubs.Schema.Currency value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        from_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Currency from = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFrom() {
        
        from_ = 0;
        onChanged();
        return this;
      }

      private int to_ = 0;
      /**
       * <code>.Currency to = 2;</code>
       * @return The enum numeric value on the wire for to.
       */
      public int getToValue() {
        return to_;
      }
      /**
       * <code>.Currency to = 2;</code>
       * @param value The enum numeric value on the wire for to to set.
       * @return This builder for chaining.
       */
      public Builder setToValue(int value) {
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Currency to = 2;</code>
       * @return The to.
       */
      public hajji.mohammed.stubs.Schema.Currency getTo() {
        @SuppressWarnings("deprecation")
        hajji.mohammed.stubs.Schema.Currency result = hajji.mohammed.stubs.Schema.Currency.valueOf(to_);
        return result == null ? hajji.mohammed.stubs.Schema.Currency.UNRECOGNIZED : result;
      }
      /**
       * <code>.Currency to = 2;</code>
       * @param value The to to set.
       * @return This builder for chaining.
       */
      public Builder setTo(hajji.mohammed.stubs.Schema.Currency value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        to_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Currency to = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTo() {
        
        to_ = 0;
        onChanged();
        return this;
      }

      private double amount_ ;
      /**
       * <code>double amount = 3;</code>
       * @return The amount.
       */
      public double getAmount() {
        return amount_;
      }
      /**
       * <code>double amount = 3;</code>
       * @param value The amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmount(double value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double amount = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmount() {
        
        amount_ = 0D;
        onChanged();
        return this;
      }

      private double result_ ;
      /**
       * <code>double result = 4;</code>
       * @return The result.
       */
      public double getResult() {
        return result_;
      }
      /**
       * <code>double result = 4;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(double value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double result = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        
        result_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ObjectResponse)
    }

    // @@protoc_insertion_point(class_scope:ObjectResponse)
    private static final hajji.mohammed.stubs.Schema.ObjectResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new hajji.mohammed.stubs.Schema.ObjectResponse();
    }

    public static hajji.mohammed.stubs.Schema.ObjectResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ObjectResponse>
        PARSER = new com.google.protobuf.AbstractParser<ObjectResponse>() {
      @java.lang.Override
      public ObjectResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ObjectResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ObjectResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ObjectResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public hajji.mohammed.stubs.Schema.ObjectResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ObjectRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ObjectRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ObjectResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ObjectResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014schema.proto\"O\n\rObjectRequest\022\027\n\004from\030" +
      "\001 \001(\0162\t.Currency\022\025\n\002to\030\002 \001(\0162\t.Currency\022" +
      "\016\n\006amount\030\003 \001(\001\"`\n\016ObjectResponse\022\027\n\004fro" +
      "m\030\001 \001(\0162\t.Currency\022\025\n\002to\030\002 \001(\0162\t.Currenc" +
      "y\022\016\n\006amount\030\003 \001(\001\022\016\n\006result\030\004 \001(\001*2\n\010Cur" +
      "rency\022\013\n\007UNKNOWN\020\000\022\010\n\004EURO\020\001\022\007\n\003USD\020\002\022\006\n" +
      "\002DH\020\0032\346\001\n\rBanqueService\022-\n\nunaryModel\022\016." +
      "ObjectRequest\032\017.ObjectResponse\0226\n\021server" +
      "StreamModel\022\016.ObjectRequest\032\017.ObjectResp" +
      "onse0\001\0226\n\021clientStreamModel\022\016.ObjectRequ" +
      "est\032\017.ObjectResponse(\001\0226\n\017fullStreamMode" +
      "l\022\016.ObjectRequest\032\017.ObjectResponse(\0010\001B\026" +
      "\n\024hajji.mohammed.stubsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ObjectRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ObjectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ObjectRequest_descriptor,
        new java.lang.String[] { "From", "To", "Amount", });
    internal_static_ObjectResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ObjectResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ObjectResponse_descriptor,
        new java.lang.String[] { "From", "To", "Amount", "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
